### ISSUE TITLE
[BUG] Purchasing multiple items at once in a store with max_stack_size set to 1 will incorrectly stack in the player's backpack

### ISSUE THREAD

**Issue by MCLMLI** [Ghost-chu/QuickShop-Hikari#1730] opened 2024-08-23 15:20 UTC
### Description

Purchasing multiple items at once in a store with max_stack_size set to 1 will incorrectly stack in the player's backpack

### Steps to reproduce

1. Create a shop for an item with max_stack_size=1
2. The player buys multiple such items at once (enter 1 or more when asked for the purchase quantity)
3. Items are incorrectly stacked in the player's backpack

### Expected Behaviour

Make items stack correctly in the player's backpack

### Screenshots

![2024-08-23_23 19 06](https://github.com/user-attachments/assets/5203d5c0-3fdb-4f9f-ab39-6a8a5b8ec585)
![2024-08-23_23 19 20](https://github.com/user-attachments/assets/4289d819-d9c1-41b3-8897-ced7bd18d9f7)
![2024-08-23_23 19 29](https://github.com/user-attachments/assets/3c574612-90bd-41b8-8a27-96b387541e1e)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FAWJjwC7u7T

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment] 2024-08-23 15:24
> ### Description
> Purchasing multiple items at once in a store with max_stack_size set to 1 will incorrectly stack in the player's backpack
> 
> ### Steps to reproduce
> 1. Create a shop for an item with max_stack_size=1
> 2. The player buys multiple such items at once (enter 1 or more when asked for the purchase quantity)
> 3. Items are incorrectly stacked in the player's backpack
> 
> ### Expected Behaviour
> Make items stack correctly in the player's backpack
> 
> ### Screenshots
> ![2024-08-23_23 19 06](https://private-user-images.githubusercontent.com/137788977/360978618-5203d5c0-3fdb-4f9f-ab39-6a8a5b8ec585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY4MzgsIm5iZiI6MTcyNDQyNjUzOCwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NjE4LTUyMDNkNWMwLTNmZGItNGY5Zi1hYjM5LTZhOGE1YjhlYzU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTE1ZjljYTBjMDQ5YjgzNjA5Yzc2N2IzMjEwZTcxYjA2ODI2Y2MwODA2MTY2N2I0MDY4MGU4ZTc3ZTkzZWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pVxze2nHbEwd0fHzxyz1Nuqokes6AM_kIYZinyQgVQM) ![2024-08-23_23 19 20](https://private-user-images.githubusercontent.com/137788977/360978681-4289d819-d9c1-41b3-8897-ced7bd18d9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY4MzgsIm5iZiI6MTcyNDQyNjUzOCwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NjgxLTQyODlkODE5LWQ5YzEtNDFiMy04ODk3LWNlZDdiZDE4ZDlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTg3ZDU2ODczYmQ3Njk3NjQ4NTFmMzE4YWQ0NmE0ZTJhYTA1NTMwODAzZjM5ODA4Yzk5Zjk3ZTY5YTZmYWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K0en55brIDhJJmPnGXPVFzRwY_7AdjGo2HtYdRiJ1KQ) ![2024-08-23_23 19 29](https://private-user-images.githubusercontent.com/137788977/360978700-3c574612-90bd-41b8-8a27-96b387541e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY4MzgsIm5iZiI6MTcyNDQyNjUzOCwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NzAwLTNjNTc0NjEyLTkwYmQtNDFiOC04YTI3LTk2YjM4NzU0MWUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzdlYTRhODUwYWM4YWNjYzliMjQyZGEzMDgwNzM4MGVjNDQxMTk0ZTYzZjBmMGY4MWYyNzMzMTIzMWE2NTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pg7ZRqFkR7bjgfgb2PLMlWydhdroovp1-OX9OcPdF18)
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FAWJjwC7u7T
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [x]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

This is less of

> ### Description
> Purchasing multiple items at once in a store with max_stack_size set to 1 will incorrectly stack in the player's backpack
> 
> ### Steps to reproduce
> 1. Create a shop for an item with max_stack_size=1
> 2. The player buys multiple such items at once (enter 1 or more when asked for the purchase quantity)
> 3. Items are incorrectly stacked in the player's backpack
> 
> ### Expected Behaviour
> Make items stack correctly in the player's backpack
> 
> ### Screenshots
> ![2024-08-23_23 19 06](https://private-user-images.githubusercontent.com/137788977/360978618-5203d5c0-3fdb-4f9f-ab39-6a8a5b8ec585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY5MjYsIm5iZiI6MTcyNDQyNjYyNiwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NjE4LTUyMDNkNWMwLTNmZGItNGY5Zi1hYjM5LTZhOGE1YjhlYzU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjA0NDI5ZThmNDllNmZmNjQ2M2QwNTBlYjcyNGI3M2I5MjVmMzdiODQ2Mzc4YTgzNmVkM2E1NDY1MDNkZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.olGYcmV3qv2b62gyCmQlHJ69CkeKdpEBaWCjZjRnRlI) ![2024-08-23_23 19 20](https://private-user-images.githubusercontent.com/137788977/360978681-4289d819-d9c1-41b3-8897-ced7bd18d9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY5MjYsIm5iZiI6MTcyNDQyNjYyNiwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NjgxLTQyODlkODE5LWQ5YzEtNDFiMy04ODk3LWNlZDdiZDE4ZDlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTIzYWUyNjEzM2QxZmJjZDVhMjlhOTc2OTQ4NDEwOTJlZjgxMGI4ODFlZGZhNDhkMjNkZTQwMWM1NWJkMTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H6VJmt4tnyHMdBRlyL3eOZYaYkqZXpiXSypslfssbt8) ![2024-08-23_23 19 29](https://private-user-images.githubusercontent.com/137788977/360978700-3c574612-90bd-41b8-8a27-96b387541e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjY5MjYsIm5iZiI6MTcyNDQyNjYyNiwicGF0aCI6Ii8xMzc3ODg5NzcvMzYwOTc4NzAwLTNjNTc0NjEyLTkwYmQtNDFiOC04YTI3LTk2YjM4NzU0MWUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTIzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDllYzFiMDllMGUzNWY3YzBlNjY4ZTM2ZTExZjgyMjQ4MGRhNTQyODgyY2UzMjE1ODhlNmZkYmQ2YmNhZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yohjpYuDoULJrUPbjpZgEJF_jq2qljvrAZ20U9iPFE0)
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FAWJjwC7u7T
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [x]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

Are you using the custom stack size configuration in config.yml? This is something that would be resolved by that, going through the individual max stack size setting for item data isn't serving supported so if that's what you're looking for then you'll have to make that a feature request, not a bug report, which I don't think is something that should be added, because you can already set the max stack by material . I.e. golden carrots. https://github.com/QuickShop-Community/QuickShop-Hikari/blob/378a6c186aa4160417874870ab6209b744f6583c/quickshop-bukkit/src/main/resources/config.yml#L557

**Comment by creatorfromhell** [comment] 2024-08-23 15:26
Closing as there is a config option for this.

**Closed as completed by creatorfromhell** 2024-08-23 15:26 UTC

**Comment by MCLMLI** [comment] 2024-08-23 15:28
I haven't adjusted this option, I think the default one is off, and I have confirmed that I have turned it off

**Comment by MCLMLI** [comment] 2024-08-23 15:29
![image](https://github.com/user-attachments/assets/73b6ab27-f677-4670-a166-7264361024d1)
