### ISSUE TITLE
[BUG] TNE support is broken

### ISSUE THREAD

**Issue by Soarinskyy** [Ghost-chu/QuickShop-Hikari#1698] opened 2024-07-29 09:35 UTC
### Description

I tried to do /quickshop create this happened

### Steps to reproduce

/quickshop create 5

### Expected Behaviour

please help me or fix this bug

### Screenshots

![image](https://github.com/user-attachments/assets/4cc8892d-931f-4b50-803a-6a8e48eddf3b)

### `/quickshop paste` URL
https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FCdNJQM06mR

### Additional Context
Server Logs  [latest.log](https://github.com/user-attachments/files/16410806/latest.log)

_No response_

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment] 2024-07-29 09:37
please also upload your server full logs

**Comment by creatorfromhell** [comment] 2024-07-30 02:18
Seems like the economy system didn't load.

**Comment by Soarinskyy** [comment] 2024-07-30 06:43
> Seems like the economy system didn't load.

How do i load it

**Comment by YuanYuanOwO** [comment] 2024-07-30 07:54
If I remember correctly, here are his log entries
```
[09:15:29] [pool-16-thread-10/INFO]: [QuickShop-Hikari] [DEBUG] [Server thread/INFO] (QuickShop$EconomyLoader#load:1175) The task [Loading Economy Bridge] has finished in 1ms.
[09:15:29] [Server thread/WARN]: [QuickShop-Hikari] Task #34 for QuickShop-Hikari v6.2.0.6 generated an exception
java.lang.NoClassDefFoundError: com/ghostchu/quickshop/shade/tne/core/utils/exceptions/InvalidTransactionException
	at QuickShop-Hikari-6.2.0.6.jar/com.ghostchu.quickshop.QuickShop$EconomyLoader.loadTNE(QuickShop.java:1264) ~[QuickShop-Hikari-6.2.0.6.jar:?]
	at QuickShop-Hikari-6.2.0.6.jar/com.ghostchu.quickshop.QuickShop$EconomyLoader.setupEconomy(QuickShop.java:1194) ~[QuickShop-Hikari-6.2.0.6.jar:?]
	at QuickShop-Hikari-6.2.0.6.jar/com.ghostchu.quickshop.QuickShop$EconomyLoader.load(QuickShop.java:1176) ~[QuickShop-Hikari-6.2.0.6.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-21-0a1b133]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-21-0a1b133]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[paper-1.21.jar:1.21-21-0a1b133]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-21-0a1b133]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.ghostchu.quickshop.shade.tne.core.utils.exceptions.InvalidTransactionException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 8 more
```

**Comment by creatorfromhell** [comment] 2024-08-04 05:56
This should be fixed in the dev build.

**Comment by creatorfromhell** [comment] 2024-08-06 23:22
@Soarinskyy Try this one inside the zip.
[QuickShop-Hikari-6.2.0.7 (1).zip](https://github.com/user-attachments/files/16516546/QuickShop-Hikari-6.2.0.7.1.zip)

**Comment by creatorfromhell** [comment] 2024-08-10 05:05
Closing as can't reproduce with the new dev build.

**Closed as completed by creatorfromhell** 2024-08-10 05:05 UTC
