### ISSUE TITLE
[BUG] Plugin causes "Invalid move player packet received" kicks upon teleports with Papers anti-xray enabled

### ISSUE THREAD

**Issue by x86-39** [Ghost-chu/QuickShop-Hikari#517] opened 2022-11-13 03:19 UTC
### Description

Upon teleporting some distance, players are occasionally kicked with an invalid move player packet error. This error was narrowed down to being caused by QuickShop (Both reremake and Hikari cause this) after sequentially removing plugins from the server one by one until the kick no longer happened, and then adding QuickShop back to verify that the kick once again occurred after reinstalling it. Appears to only happen when one of the teleportation locations involved has shops nearby.

Minimum number of plugins installed that I tried while still getting the kick:
EssentialsX
EssentialsX AntiBuild
EssentialsX Chat
EssentialsX Protect
EssentialsX Spawn
ProtocolLib
QuickShop Hikari 3.3.0.1

Console output during kick (/b is our server's alias for the Essentials /back command):
```
13:58:47
maeeeeee issued server command: /b
maeeeeee issued server command: /b
13:58:48
maeeeeee issued server command: /b
maeeeeee issued server command: /b
maeeeeee lost connection: Invalid move player packet received
-maeeeeee has left for now.
```

Spamming /back from EssentialsX between two areas far apart where at least one of the areas has a QuickShop shop loaded.
I'm using a mod [Command Macros](https://www.curseforge.com/minecraft/mc-mods/command-macros) to send /back every 100ms.
Of course spamming it so much isn't representative, but this is a way to replicate the issue. This can be replicated on a vanilla client too by just typing the command a lot, but I used the macro for convenience. This just often happens out of nowhere to players when teleporting. 

It seems to happen to some players more than others so connection speed could be a part of it, but I'm seeing it happen to about every player. Checking through logs we've had this happen 985 times since October 15th.
This information is from QuickShop Reremake, but this was reproduced on QuickShop Hikari too, so I doubt it'd be any different.

### Steps to reproduce

1. Teleport to a location. Several different plugins were used for teleporting, such as EssentialsX, MyWarp, and others, and each caused the issue.
2. Player is occasionally kicked from the server.

To consistently reproduce using EssentialsX, teleport somewhere (/tpr works for this) and then spam /back until the issue occurs.

### Expected Behaviour

Plugin should not be causing players to be kicked upon teleports.

### Screenshots

[Minecraft.2022.11.12.-.13.57.55.03.mp4](https://user-images.githubusercontent.com/52181624/201490494-7fb29f92-e23a-4707-81b7-b76f040abeee.mp4)

### `/qs paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FV6Wy3DZ5yz

### Additional Context

Duplicate of https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/255

Can replicate with paper-1.19.2-265 with the following plugins:

* Vault
* QuickShop Hikari 3.3.0.1
* Protocollib
* EssentialsX

All configs set to default , except for:
Changed `config/paper-world-defaults.yml` and setting `anticheat.anti-xray.enabled` to `true`.

**Comment by maeeeeee** [comment] 2022-11-13 05:16
Appears to be related to virtual item displays: https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/255#issuecomment-1312641753

**Comment by Ghost-chu** [comment] 2022-11-13 07:51
> Appears to be related to virtual item displays: [PotatoCraft-Studio/QuickShop-Reremake#255 (comment)](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/255#issuecomment-1312641753)

I think it will take some time to investigate the cause, there is no ETA guarantee, but I will try

**Comment by Ghost-chu** [comment] 2022-11-13 08:03
@diademiemi @maeeeeee Could you try reproduce it again? And create a quickshop paste immediately, and upload them with server full logs (`latest.log`).

**Comment by Ghost-chu** [comment] 2022-11-13 08:12
Note comment (it can be edited anytime once we found any useful infomations)

> after update 1.19, this problem was occur (Invalid move player packet received)
player has disconnected with join server or warp command. (im now using lastest version of velocity)
i set moved-too-quickly-multiplier, moved-wrongly-threshold with very high value, but it still happend.
also update lastest 1.19 dev version of protocollib, delete citizens, images plugin
i stuck with this problem almost a week.
is anybody known this issues?
github : https://github.com/PaperMC/Paper/issues/8222 

> i may have found a bug in paper's new chunk system
sometimes when a player teleports if prevent moving into unloaded chunks is enabled, and the area they are teleporting to is not loaded in the server's ram the player will get kicked from the server with this message
<player> lost connection: Invalid move player packet received
it could be because with the chunk system overhaul the server is no longer loading chunks before it attempts to teleport

**Comment by Ghost-chu** [comment] 2022-11-13 09:12
Cannot reproduce on Paper git-Paper-265 (MC: 1.19.2), try update your server core up-to-date

**Comment by Ghost-chu** [comment] 2022-11-13 09:18
https://user-images.githubusercontent.com/30802565/201514682-e94064e4-f42b-4608-aa3c-c89421740449.mp4

**Comment by Ghost-chu** [comment] 2022-11-13 09:34
oh okay i got it reproduced, i will start investigate now

**Comment by Ghost-chu** [comment] 2022-11-13 12:15
Compare reference:

1. Vanilla Minecraft /tp + No Packet Sending : OK!
2. Vanilla Minecraft /tp + Packet Sending : OK!
3. BukkitAPI sync teleport + No Packet Sending : OK!
4. BukkitAPI sync teleport + Packet Sending : OK!
5. PaperAPI AsyncTeleport + No Packet Sending : OK!
6. PaperAPI AsyncTeleport + PacketSending: KICK

**Comment by maeeeeee** [comment] 2022-11-14 04:36
Further details added here, seems duplicate packets are being sent: https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/255#issuecomment-1312873111

**Comment by Ghost-chu** [comment] 2022-11-14 04:39
thanks for comment!
I've already working with sandtechnology on this issue.
Currently it seems is a Paper bug, we're still looking into it.

---Original---
From: ***@***.***&gt;
Date: Mon, Nov 14, 2022 12:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Ghost-chu/QuickShop-Hikari] [BUG] Plugin causes "Invalid moveplayer packet received" kicks upon teleports with Papers anti-xray enabled(Issue #517)




 
Further details added here, seems duplicate packets are being sent: PotatoCraft-Studio/QuickShop-Reremake#255 (comment)

**Comment by Ghost-chu** [comment] 2022-11-27 16:58
Paper merged patch in build 297, update Paper and should works now!

**Closed as completed by Ghost-chu** 2022-11-27 16:58 UTC
